### ISSUE TITLE
Question: Any difference between using a hard pwm pin or not?

### ISSUE THREAD

**Issue by Fireflaker** [Palatis/arduino-softpwm#8]

**Comment by Fireflaker** [comment]
What is the approximate usable frequency range for a 16Mhz clock? Does clock cycle divider work when using a soft pwm/ hard pwm pin? Or the 0-255 counter handles all the work adjusting frequency.

Thank you very much for this library.

**Comment by Palatis** [comment]
1. it's a combination of pwm channels, pwm levels, and pwm frequency. you want to update the pin as fast as you can (fast enough so that persistent of vision comes into play), but still leave enough processing power to run your own code. use the `printInterruptLoad()` method to determine if the current combination of values is suitable for your application.

2. this lib is a softpwm lib, doesn't use any hw pwm support.

**Comment by Fireflaker** [comment]
Thank you very much！
